version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis-stack
    env_file:
      - .env.dev
    command:
      - "redis-stack-server"
      - "--save 90 1"
      - "--save 30 10"
      - "--save 6 10000"
      - "--requirepass ${REDIS_PASSWORD}"
  app:
    restart: always
    build: .
    command: poetry run uvicorn main:app --workers 2 --host=0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    env_file:
      - .env.dev
    depends_on:
      - redis
volumes:
  redis-data:
    driver: local
