version: "3.9"
services:
  # TODO:  Memory overcommit must be enabled! Without it
  redis:
    image: redis/redis-stack-server:latest
    container_name: jarvis-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis-stack
    env_file:
      - .env
    command:
      - "redis-stack-server"
      - "--save 90 1"
      - "--save 30 10"
      - "--save 6 10000"
      - "--requirepass ${REDIS_PASSWORD}"
    networks:
      - my-network
  test:
    image: alpine
    container_name: jarvis-api
    command: ping redis
    networks:
      - my-network
    depends_on:
      - redis
networks:
  my-network:
volumes:
  redis-data:
    # https://learn.microsoft.com/ko-kr/azure/storage/files/storage-files-introduction
    driver: azure_file
    driver_opts:
      share_name: jarvis0redis
      storage_account_name: jarvis0storage0account
# > docker logs -f jarvis_jarvis-api
# PING redis (127.0.0.1): 56 data bytes
# 64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.047 ms
# 64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.049 ms
# 64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.044 ms
# 64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.065 ms
# 64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.082 ms
# 64 bytes from 127.0.0.1: seq=5 ttl=64 time=0.049 ms
