version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: jarvis0redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis-stack
    env_file:
      - .env.dev
    command:
      - "redis-stack-server"
      - "--save 90 1"
      - "--save 30 10"
      - "--save 6 10000"
      - "--requirepass ${REDIS_PASSWORD}"
  app:
    restart: always
    build: .
    volumes:
      - ./src:/src/
      - ./poetry.lock:/src/poetry.lock
      - ./pyproject.toml:/src/pyproject.toml
    command: uvicorn main:app --workers 2 --host=0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - redis
volumes:
  redis-data:
    driver: local
