version: "3.9"
services:
  # TODO:  Memory overcommit must be enabled! Without it
  redis:
    image: redis/redis-stack-server:latest
    container_name: jarvis-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis-stack
    env_file:
      - .env
    command:
      - "redis-stack-server"
      - "--save 90 1"
      - "--save 30 10"
      - "--save 6 10000"
      - "--requirepass ${REDIS_PASSWORD}"
  app:
    image: jarvisgptacr.azurecr.io/jarvis_app:v1
    container_name: jarvis-api
    build: .
    restart: always
    # TODO: --proxy-headers, nginx, domain attatch
    command: uvicorn main:app --workers 3 --host=0.0.0.0 --port 80
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    container_name: jarvis-nginx
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  certbot:
    container_name: jarvis-certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  redis-data:
    driver: local
